name = "Algebra"
uuid = "6e63c486-1419-420a-94be-1e42310aacd9"
authors = ["Ouroboros42 <lucas.gathercole@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
